In [120]:
from google.colab import drive
drive.mount('/content/drive/', force_remount=True)
import pandas as pd
path_to_file = '/content/drive/My Drive/dl-udemy/shakespeare.txt'
text = open(path_to_file, 'r').read()

Mounted at /content/drive/


In [121]:
%tensorflow_version 2.2.0
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

# IGNORE THE CONTENT OF THIS CELL
# tf.compat.v1.disable_eager_execution()

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [122]:
!pip install tensorflow==2.8.0
tf.__version__

'2.8.0'

In [123]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [124]:
# The unique characters in the file
vocab = sorted(set(text))
print(vocab)
len(vocab)

['\n', ' ', '!', '"', '&', "'", '(', ')', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '>', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '|', '}']


84

In [125]:
char_to_ind = {u:i for i, u in enumerate(vocab)}

In [126]:
char_to_ind

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '&': 4,
 "'": 5,
 '(': 6,
 ')': 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '0': 11,
 '1': 12,
 '2': 13,
 '3': 14,
 '4': 15,
 '5': 16,
 '6': 17,
 '7': 18,
 '8': 19,
 '9': 20,
 ':': 21,
 ';': 22,
 '<': 23,
 '>': 24,
 '?': 25,
 'A': 26,
 'B': 27,
 'C': 28,
 'D': 29,
 'E': 30,
 'F': 31,
 'G': 32,
 'H': 33,
 'I': 34,
 'J': 35,
 'K': 36,
 'L': 37,
 'M': 38,
 'N': 39,
 'O': 40,
 'P': 41,
 'Q': 42,
 'R': 43,
 'S': 44,
 'T': 45,
 'U': 46,
 'V': 47,
 'W': 48,
 'X': 49,
 'Y': 50,
 'Z': 51,
 '[': 52,
 ']': 53,
 '_': 54,
 '`': 55,
 'a': 56,
 'b': 57,
 'c': 58,
 'd': 59,
 'e': 60,
 'f': 61,
 'g': 62,
 'h': 63,
 'i': 64,
 'j': 65,
 'k': 66,
 'l': 67,
 'm': 68,
 'n': 69,
 'o': 70,
 'p': 71,
 'q': 72,
 'r': 73,
 's': 74,
 't': 75,
 'u': 76,
 'v': 77,
 'w': 78,
 'x': 79,
 'y': 80,
 'z': 81,
 '|': 82,
 '}': 83}

In [127]:
ind_to_char = np.array(vocab)

In [128]:
ind_to_char

array(['\n', ' ', '!', '"', '&', "'", '(', ')', ',', '-', '.', '0', '1',
       '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '>', '?',
       'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
       '[', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i',
       'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v',
       'w', 'x', 'y', 'z', '|', '}'], dtype='<U1')

In [129]:
encoded_text = np.array([char_to_ind[c] for c in text])

In [130]:
encoded_text

array([ 0,  1,  1, ..., 30, 39, 29])

In [131]:
sample = text[:20]
sample

'\n                   '

In [132]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [133]:
line = "From fairest creatures we desire increase"

In [134]:
len(line)

41

In [135]:
part_stanza = """From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,"""

In [136]:
len(part_stanza)

131

In [137]:
seq_len = 120

In [138]:
total_num_seq = len(text)//(seq_len+1)

In [139]:
total_num_seq

45005

In [140]:
# Create Training Sequences
char_dataset = tf.data.Dataset.from_tensor_slices(encoded_text)

for i in char_dataset.take(500):
     print(ind_to_char[i.numpy()])



 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
1


 
 
F
r
o
m
 
f
a
i
r
e
s
t
 
c
r
e
a
t
u
r
e
s
 
w
e
 
d
e
s
i
r
e
 
i
n
c
r
e
a
s
e
,


 
 
T
h
a
t
 
t
h
e
r
e
b
y
 
b
e
a
u
t
y
'
s
 
r
o
s
e
 
m
i
g
h
t
 
n
e
v
e
r
 
d
i
e
,


 
 
B
u
t
 
a
s
 
t
h
e
 
r
i
p
e
r
 
s
h
o
u
l
d
 
b
y
 
t
i
m
e
 
d
e
c
e
a
s
e
,


 
 
H
i
s
 
t
e
n
d
e
r
 
h
e
i
r
 
m
i
g
h
t
 
b
e
a
r
 
h
i
s
 
m
e
m
o
r
y
:


 
 
B
u
t
 
t
h
o
u
 
c
o
n
t
r
a
c
t
e
d
 
t
o
 
t
h
i
n
e
 
o
w
n
 
b
r
i
g
h
t
 
e
y
e
s
,


 
 
F
e
e
d
'
s
t
 
t
h
y
 
l
i
g
h
t
'
s
 
f
l
a
m
e
 
w
i
t
h
 
s
e
l
f
-
s
u
b
s
t
a
n
t
i
a
l
 
f
u
e
l
,


 
 
M
a
k
i
n
g
 
a
 
f
a
m
i
n
e
 
w
h
e
r
e
 
a
b
u
n
d
a
n
c
e
 
l
i
e
s
,


 
 
T
h
y
 
s
e
l
f
 
t
h
y
 
f
o
e
,
 
t
o
 
t
h
y
 
s
w
e
e
t
 
s
e
l
f
 
t
o
o
 
c
r
u
e
l
:


 
 
T
h
o
u
 
t
h
a
t
 
a
r
t
 
n
o
w
 
t
h
e
 
w
o
r
l
d
'
s
 
f
r
e
s
h
 
o
r
n
a
m
e
n
t
,


 
 
A
n
d
 
o
n
l
y
 
h
e
r
a
l
d
 
t
o
 
t
h
e
 
g
a
u
d
y
 
s
p
r
i
n
g
,


 
 
W
i
t
h
i
n
 
t
h
i
n
e
 
o
w
n
 
b
u


In [141]:
sequences = char_dataset.batch(seq_len+1, drop_remainder=True)

In [142]:
def create_seq_targets(seq):
    input_txt = seq[:-1]
    target_txt = seq[1:]
    return input_txt, target_txt

In [143]:
dataset = sequences.map(create_seq_targets)

In [144]:
for input_txt, target_txt in  dataset.take(1):
    print(input_txt.numpy())
    print(''.join(ind_to_char[input_txt.numpy()]))
    print('\n')
    print(target_txt.numpy())
    # There is an extra whitespace!
    print(''.join(ind_to_char[target_txt.numpy()]))

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But


[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1]
                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But 


In [145]:
# Batch size
batch_size = 128

# Buffer size to shuffle the dataset so it doesn't attempt to shuffle
# the entire sequence in memory. Instead, it maintains a buffer in which it shuffles elements
buffer_size = 10000

dataset = dataset.shuffle(buffer_size).batch(batch_size, drop_remainder=True)

In [146]:
dataset

<BatchDataset element_spec=(TensorSpec(shape=(128, 120), dtype=tf.int64, name=None), TensorSpec(shape=(128, 120), dtype=tf.int64, name=None))>

In [147]:
# Length of the vocabulary in chars
vocab_size = len(vocab)

# The embedding dimension
embed_dim = 64

# Number of RNN units
rnn_neurons = 1026

In [148]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import LSTM,Dense,Embedding,Dropout,GRU
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [149]:
def sparse_cat_loss(y_true,y_pred):
    return sparse_categorical_crossentropy(y_true, y_pred, from_logits=True)

In [150]:
help(sparse_categorical_crossentropy)

Help on function sparse_categorical_crossentropy in module keras.losses:

sparse_categorical_crossentropy(y_true, y_pred, from_logits=False, axis=-1)
    Computes the sparse categorical crossentropy loss.
    
    Standalone usage:
    
    >>> y_true = [1, 2]
    >>> y_pred = [[0.05, 0.95, 0], [0.1, 0.8, 0.1]]
    >>> loss = tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred)
    >>> assert loss.shape == (2,)
    >>> loss.numpy()
    array([0.0513, 2.303], dtype=float32)
    
    Args:
      y_true: Ground truth values.
      y_pred: The predicted values.
      from_logits: Whether `y_pred` is expected to be a logits tensor. By default,
        we assume that `y_pred` encodes a probability distribution.
      axis: Defaults to -1. The dimension along which the entropy is
        computed.
    
    Returns:
      Sparse categorical crossentropy loss value.



In [151]:
def create_model(vocab_size, embed_dim, rnn_neurons, batch_size):
    model = Sequential()
    model.add(Embedding(vocab_size, embed_dim,batch_input_shape=[batch_size, None]))
    model.add(GRU(rnn_neurons,return_sequences=True,stateful=True,recurrent_initializer='glorot_uniform'))
    # Final Dense Layer to Predict
    model.add(Dense(vocab_size))
    model.compile(optimizer='adam', loss=sparse_cat_loss)
    return model

In [152]:
model = create_model(
  vocab_size = vocab_size,
  embed_dim=embed_dim,
  rnn_neurons=rnn_neurons,
  batch_size=batch_size)

In [153]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (128, None, 64)           5376      
                                                                 
 gru_3 (GRU)                 (128, None, 1026)         3361176   
                                                                 
 dense_3 (Dense)             (128, None, 84)           86268     
                                                                 
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


In [154]:
for input_example_batch, target_example_batch in dataset.take(1):

  # Predict off some random batch
  example_batch_predictions = model(input_example_batch)

  # Display the dimensions of the predictions
  print(example_batch_predictions.shape, " <=== (batch_size, sequence_length, vocab_size)")

(128, 120, 84)  <=== (batch_size, sequence_length, vocab_size)


In [155]:
example_batch_predictions

<tf.Tensor: shape=(128, 120, 84), dtype=float32, numpy=
array([[[ 1.2023585e-02,  3.4321682e-04, -4.7598439e-03, ...,
         -6.2325125e-06,  6.1474938e-04,  2.5284297e-03],
        [-1.4337656e-03, -3.5868720e-03, -1.8561069e-03, ...,
         -6.5624402e-03,  5.1127706e-04, -6.1292276e-03],
        [-2.5401160e-03, -4.5123990e-03,  1.8669143e-03, ...,
         -2.1622126e-04, -1.4197617e-03, -1.1050051e-02],
        ...,
        [ 1.6360207e-02, -8.5765094e-04, -8.0182161e-03, ...,
          2.9096389e-03,  1.5304815e-03, -7.8753009e-04],
        [ 6.7674583e-03,  6.5646269e-03, -1.7499449e-03, ...,
          1.6185427e-03, -1.1004932e-03, -4.0652542e-03],
        [ 3.3886894e-03,  7.0219105e-03,  2.1952023e-04, ...,
          2.1646125e-03, -3.8311323e-03,  4.9668080e-03]],

       [[ 1.5366338e-03, -3.4030315e-03, -3.2538427e-03, ...,
         -3.3607430e-04, -2.3121121e-03,  3.8668069e-03],
        [-1.5510101e-03,  4.4541224e-03, -2.1221333e-03, ...,
          1.6160194e-03, -3

In [156]:
sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)

In [157]:
sampled_indices

<tf.Tensor: shape=(120, 1), dtype=int64, numpy=
array([[70],
       [ 9],
       [50],
       [66],
       [24],
       [23],
       [12],
       [74],
       [47],
       [46],
       [16],
       [53],
       [39],
       [23],
       [20],
       [50],
       [62],
       [ 7],
       [34],
       [65],
       [ 0],
       [25],
       [ 4],
       [ 6],
       [75],
       [66],
       [77],
       [11],
       [ 1],
       [ 7],
       [ 5],
       [14],
       [29],
       [62],
       [53],
       [60],
       [42],
       [81],
       [44],
       [83],
       [ 2],
       [73],
       [19],
       [52],
       [ 5],
       [61],
       [25],
       [82],
       [36],
       [39],
       [44],
       [62],
       [80],
       [72],
       [50],
       [77],
       [ 1],
       [50],
       [81],
       [80],
       [ 3],
       [67],
       [29],
       [ 8],
       [46],
       [ 5],
       [19],
       [58],
       [43],
       [ 1],
       [ 0],
       [52],
       [ 2],
   

In [158]:
# Reformat to not be a lists of lists
sampled_indices = tf.squeeze(sampled_indices,axis=-1).numpy()

In [159]:
sampled_indices

array([70,  9, 50, 66, 24, 23, 12, 74, 47, 46, 16, 53, 39, 23, 20, 50, 62,
        7, 34, 65,  0, 25,  4,  6, 75, 66, 77, 11,  1,  7,  5, 14, 29, 62,
       53, 60, 42, 81, 44, 83,  2, 73, 19, 52,  5, 61, 25, 82, 36, 39, 44,
       62, 80, 72, 50, 77,  1, 50, 81, 80,  3, 67, 29,  8, 46,  5, 19, 58,
       43,  1,  0, 52,  2, 61, 40, 16, 49, 37, 41, 26, 65, 11, 58,  4, 36,
       70, 12, 47,  7, 66, 37, 12, 16, 40, 48, 72,  5,  7, 67, 60, 67, 68,
       23, 27, 66, 71, 62, 63, 49, 51, 79,  4, 67, 15, 57, 22, 53,  2, 35,
       21])

In [160]:
print("Given the input seq: \n")
print("".join(ind_to_char[input_example_batch[0]]))
print('\n')
print("Next Char Predictions: \n")
print("".join(ind_to_char[sampled_indices ]))

Given the input seq: 

 moss'd with age,  
    And high top bald with dry antiquity,
    A wretched ragged man, o'ergrown with hair,
    Lay sl


Next Char Predictions: 

o-Yk><1sVU5]N<9Yg)Ij
?&(tkv0 )'3Dg]eQzS}!r8['f?|KNSgyqYv Yzy"lD,U'8cR 
[!fO5XLPAj0c&Ko1V)kL15OWq')lelm<BkpghXZx&l4b;]!J:


In [161]:
epochs = 30

In [162]:
model.fit(dataset,epochs=epochs)

Epoch 1/30
  1/351 [..............................] - ETA: 1:27:12 - loss: 4.4311

KeyboardInterrupt: 

In [163]:
# model.save('shakespeare_gen.h5')

In [164]:
from tensorflow.keras.models import load_model

In [165]:
model = create_model(vocab_size, embed_dim, rnn_neurons, batch_size=1)


path_to_file_model = '/content/drive/My Drive/dl-udemy/shakespeare_gen.h5'


model.load_weights(path_to_file_model)

model.build(tf.TensorShape([1, None]))

In [166]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (1, None, 64)             5376      
                                                                 
 gru_4 (GRU)                 (1, None, 1026)           3361176   
                                                                 
 dense_4 (Dense)             (1, None, 84)             86268     
                                                                 
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


In [167]:
def generate_text(model, start_seed,gen_size=100,temp=1.0):
    '''
    model: Trained Model to Generate Text
    start_seed: Intial Seed text in string form
    gen_size: Number of characters to generate

    Basic idea behind this function is to take in some seed text, format it so
    that it is in the correct shape for our network, then loop the sequence as
    we keep adding our own predicted characters. Similar to our work in the RNN
    time series problems.
    '''

    # Number of characters to generate
    num_generate = gen_size

    # Vecotrizing starting seed text
    input_eval = [char_to_ind[s] for s in start_seed]

    # Expand to match batch format shape
    input_eval = tf.expand_dims(input_eval, 0)

    # Empty list to hold resulting generated text
    text_generated = []

    # Temperature effects randomness in our resulting text
    # The term is derived from entropy/thermodynamics.
    # The temperature is used to effect probability of next characters.
    # Higher probability == lesss surprising/ more expected
    # Lower temperature == more surprising / less expected

    temperature = temp

    # Here batch size == 1
    model.reset_states()

    for i in range(num_generate):

        # Generate Predictions
        predictions = model(input_eval)

        # Remove the batch shape dimension
        predictions = tf.squeeze(predictions, 0)

        # Use a cateogircal disitribution to select the next character
        predictions = predictions / temperature
        predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()

        # Pass the predicted charracter for the next input
        input_eval = tf.expand_dims([predicted_id], 0)

        # Transform back to character letter
        text_generated.append(ind_to_char[predicted_id])

    return (start_seed + ''.join(text_generated))

In [168]:
print(generate_text(model,"flower",gen_size=1000))

flower'd with
    more than haunted one barrel and a rogue for your goat.
  SPEED. That I may eat looking-on she shall be the
    mettle of your habit.
  PANDARUS. Good morrow, neighbour. I think you have answer'd your father;
    Lest that this thick--makerr violate sweet Lancaster here listens of their defence.
    I am these tenives to beat him on!
    She will love, she will along with you.
  DEMETRIUS. Had oft be almost amiss?  
  SPEED. Whom should be never cross-most
  
    Is to himself; for whom the time does still
    Runs eann confession grow on me;
    Do there, unhesse will wear a case so bright.
 SCENE V.
Soucars and Cashal

  ATABELLA. Wast not the old man,
    Casca?    Here come the Emperor of my brow;
    Ensear this act of break!
  LORD. Why then?
  MALVOLIO. We have
    gall'd up with infusences will have it.
  EXETER. But what's in princely Tower, the hour of mine?
  VALENTINE. Indeed, his summer's dreams no hope I know,
    Here, lack, with groans. The oracle

Exi